name:                elements
version:             0.1.0.0
github:              "livmackintosh/elements"
license:             BSD3
author:              "Livvy Mackintosh"
maintainer:          "livvy@base.nu"
copyright:           "2019 Livvy Mackintosh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/livmackintosh/elements#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  elements-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elements

tests:
  elements-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elements
